#
# (C) Copyright 2013-2016
# Allwinner Technology Co., Ltd. <www.allwinnertech.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-$(CONFIG_SUNXI_SECURE_SYSTEM)	+= sunxi_crypto.o
obj-$(CONFIG_SUNXI_SECURE_SYSTEM)	+= sunxi_efuse.o
obj-$(CONFIG_BURN_NORMAL_EFUSE)	+= efuse_normal.o
