# Makefile for the Linux video drivers on sunxi platform.
# 16 Aug 2014, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.

obj-$(CONFIG_FB_SUNXI)     += disp/disp/
obj-$(CONFIG_LCD_SUNXI)    += disp/lcd/

obj-$(CONFIG_DISP2_SUNXI) += disp2/disp/
obj-$(CONFIG_HDMI_DISP2_SUNXI) += disp2/hdmi/
obj-$(CONFIG_HDMI2_DISP2_SUNXI) += disp2/hdmi2/
obj-$(CONFIG_TV_DISP2_SUNXI) += disp2/tv/
obj-$(CONFIG_DISP2_TV_AC200) += disp2/tv/
obj-$(CONFIG_EDP_DISP2_SUNXI) += disp2/edp/
