obj-$(CONFIG_PM_DEVFREQ)	+= devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND)	+= governor_simpleondemand.o
obj-$(CONFIG_DEVFREQ_GOV_PERFORMANCE)	+= governor_performance.o
obj-$(CONFIG_DEVFREQ_GOV_POWERSAVE)	+= governor_powersave.o
obj-$(CONFIG_DEVFREQ_GOV_USERSPACE)	+= governor_userspace.o
obj-$(CONFIG_DEVFREQ_GOV_ADAPTIVE)	+= governor_adaptive.o
obj-$(CONFIG_DEVFREQ_GOV_TEMPTRIGGER)	+= governor_temptrigger.o
obj-$(CONFIG_DEVFREQ_GOV_DSM)		+= governor_dsm.o
obj-$(CONFIG_DEVFREQ_GOV_VANS)		+= governor_vans.o

# DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos4_bus.o
obj-$(CONFIG_DEVFREQ_DRAM_FREQ)		+= dramfreq/
obj-$(CONFIG_ARM_SUNXI_DRAM_DEVFREQ)	+= sunxi_dramfreq.o
